matrix:
  include:
    - os: linux
      env: DOCKER_TAG=amd64-centos5
      sudo: required
      services:
        - docker
    - os: linux
      env: DOCKER_TAG=arm64-xenial
      sudo: required
      services:
        - docker
    - os: linux
      env: DOCKER_TAG=armhf-xenial
      sudo: required
      services:
        - docker
    - os: linux
      env: DOCKER_TAG=ppc64el-xenial
      sudo: required
      services:
        - docker
before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
script:
  - docker build -t mayeut/ljtbuilder2:${DOCKER_TAG} ${DOCKER_TAG}
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${DOCKER_PUSH}" == "1" ]; then
    docker login -u="mayeut" -p="${DOCKER_PASSWORD}";
    docker push mayeut/ljtbuilder2:${DOCKER_TAG};
    fi
